kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: assignment-service-2-pvc
spec:
  storageClassName: assignment-service-2-storageclass
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi